
spring:
  main:
    allow-bean-definition-overriding=true:
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
          web-allow:others: true
  datasource:
    username: admin
    url: jdbc:h2:mem:hospitaltestdb
    driverClassName: org.h2.Driver
    password: 'admin'
  jpa:
    hibernate:
      ddl-auto: create

jwt:
  expiration: 1
  secret: mySecret
  refreshToken:
    expiration: 1

myapp:
  access:
    token:
      secret: eyJhbGciOiJIUzI1NiIsInR5cCI6Ikp9