spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: admin
    url: jdbc:postgresql://localhost:5432/gd-medical-clinic
  jpa:
    hibernate:
      ddl-auto: create
    database-platform:
      org.hibernate.dialect.PostgreSQL9Dialect
  liquibase:
    change-log: classpath:db/changelog/changelog.yml
jwt:
  expiration: 1
  secret: mySecret
  refreshToken:
    expiration: 1
myapp:
  access:
    token:
      secret: eyJhbGciOiJIUzI1NiIsInR5cCI6Ikp9
