spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    username: admin
    url: jdbc:h2:mem:hospitaltestdb
    driverClassName: org.h2.Driver
    password: 'admin'
  jpa:
    hibernate:
      ddl-auto: create
