spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: admin
    url: jdbc:postgresql://localhost:5432/gd-medical-clinic
  jpa:
    hibernate:
      ddl-auto: validate
  #USE TO GENERATE SQL SCHEMA SCRIPT FROM JPA ENTITIES
    #properties:
      #javax:
        #persistence:
         # schema-generation:
          #  create-source: metadata
           # scripts:
            #  action: create
             # create-target: src/main/resources/db/changelog/sql/schema.sql
    database-platform:
      org.hibernate.dialect.PostgreSQL9Dialect
  liquibase:
    change-log: classpath:db/changelog/changelog.yml


